export const zeroBoard = [
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

export const initialBoard = [
  [
    {
      coords: [0, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [0, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [1, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [1, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [2, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [2, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [3, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [3, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [4, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: true, 1: true },
    },
    {
      coords: [4, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [4, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [5, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [5, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [6, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [6, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [7, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [7, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [8, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [8, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [9, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: true, 1: true },
    },
    {
      coords: [9, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [9, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [10, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [10, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [11, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [11, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [12, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [12, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
  [
    {
      coords: [13, 0],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 1],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 2],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 3],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 4],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 5],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 6],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 7],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 8],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 9],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 10],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 11],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 12],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
    {
      coords: [13, 13],
      occupant: "none",
      isPlayable: { 0: true, 1: true },
      isSeedable: { 0: false, 1: false },
    },
  ],
];
